### ISSUE TITLE
数学公式在Home页不显示

### ISSUE THREAD

**Issue by YuxinZhaozyx** [ikeq/hexo-filter-mathjax-ssr#1]
数学公式在首页无法显示，具体如下图
**Home页：**
![BI_U 8B_~Z4C0%P8K%MXDF](https://user-images.githubusercontent.com/32972764/65575374-3f3a6b80-dfa2-11e9-9c91-3201b3f77620.png)
**Post内：**
![~4Q{} _@}`{0356}5X21{MO](https://user-images.githubusercontent.com/32972764/65575433-61cc8480-dfa2-11e9-8043-01aeb2bb9b3f.png)

注：已装 hexo-filter-mathjax-ssr 插件

**Comment by ikeq** [comment]
算是这个项目的 bug 哈😄

**Comment by ikeq** [comment]
@YuxinZhaozyx 已修复，见 [[hexo-theme-inside@2.4.1](https://github.com/ikeq/hexo-theme-inside/releases/tag/2.4.1)]、 [[89d1674](https://github.com/ikeq/hexo-filter-mathjax-ssr/commit/89d1674b767abfcf1ea20ac560ee58f55466aca0)]。

需要重新替换主题静态资源，及 `npm install hexo-filter-mathjax-ssr@0.1.1`
